### ISSUE TITLE
autoreconf-2.69: automake failed with exit status: 1

### ISSUE THREAD

**Issue by salfter** [unobtanium-official/Unobtanium#11]
Tried updating Unobtanium (along with some other coins)...looks like it's switched to the autotools-based build system used by recent Bitcoin versions, so I try regenerating a suitable ebuild (I use Gentoo).  It fails.  I then try building unobtaniumd manually according to the directions in doc/build-unix.txt...that produces the following output:

```
aclocal-1.13: warning: couldn't open directory 'build-aux/m4': No such file or directory
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: copying file 'build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'build-aux/m4'.
libtoolize: copying file 'build-aux/m4/libtool.m4'
libtoolize: copying file 'build-aux/m4/ltoptions.m4'
libtoolize: copying file 'build-aux/m4/ltsugar.m4'
libtoolize: copying file 'build-aux/m4/ltversion.m4'
libtoolize: copying file 'build-aux/m4/lt~obsolete.m4'
configure.ac:5: installing 'build-aux/config.guess'
configure.ac:5: installing 'build-aux/config.sub'
configure.ac:9: installing 'build-aux/install-sh'
configure.ac:9: installing 'build-aux/missing'
Makefile.am: installing 'build-aux/depcomp'
parallel-tests: installing 'build-aux/test-driver'
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: copying file 'build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'build-aux/m4'.
libtoolize: copying file 'build-aux/m4/libtool.m4'
libtoolize: copying file 'build-aux/m4/ltoptions.m4'
libtoolize: copying file 'build-aux/m4/ltsugar.m4'
libtoolize: copying file 'build-aux/m4/ltversion.m4'
libtoolize: copying file 'build-aux/m4/lt~obsolete.m4'
configure.ac:15: installing 'build-aux/config.guess'
configure.ac:15: installing 'build-aux/config.sub'
configure.ac:25: installing 'build-aux/install-sh'
configure.ac:25: installing 'build-aux/missing'
configure.ac:879: error: required file 'share/setup.nsi.in' not found
configure.ac:879: error: required file 'share/qt/Info.plist.in' not found
configure.ac:879: error: required file 'src/test/buildenv.py.in' not found
Makefile.am:5: warning: user variable 'GZIP_ENV' defined here ...
/usr/share/automake-1.13/am/distdir.am: ... overrides Automake variable 'GZIP_ENV' defined here
Makefile.am:54: warning: user target 'distcleancheck' defined here ...
/usr/share/automake-1.13/am/distdir.am: ... overrides Automake target 'distcleancheck' defined here
src/Makefile.am: installing 'build-aux/depcomp'
src/Makefile.am:402: warning: user target '.mm.o' defined here ...
/usr/share/automake-1.13/am/depend2.am: ... overrides Automake target '.mm.o' defined here
parallel-tests: installing 'build-aux/test-driver'
autoreconf-2.69: automake failed with exit status: 1
```

I have a working build of an older version which is still running, but can't build the new version.

**Comment by salfter** [comment]
In the meantime, I've set my ebuild to use the last commit (efc1fed) before the recent changes:

https://github.com/salfter/portage/blob/master/net-p2p/unobtaniumd/unobtaniumd-9999.ebuild

**Comment by bryceweiner** [comment]
Interesting. I am researching that same issue in relation to the gitian
build system as well.

Any help or insight you might have would be appreciated.

**Comment by abuckle** [comment]
Is it a merge issue...? It looks like it's missing some files... I got it working :). See the following: 

Cheers;
Anthony

UNO build script is missing the following files: 
'share/setup.nsi.in'
'share/qt/Info.plist.in' 
'src/test/buildenv.py.in'

Found them here:
https://github.com/bitcoin/bitcoin/blob/master/share/setup.nsi.in
https://github.com/bitcoin/bitcoin/blob/master/share/qt/Info.plist.in
https://github.com/bitcoin/bitcoin/blob/master/src/test/buildenv.py.in

Added them to UNO and rebuilt. See attached image...
Built using Linux ubuntu 3.13.0-46-generic #75-Ubuntu SMP Tue Feb 10 15:24:04 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux


![screenshot from 2015-03-04 22 30 17](https://cloud.githubusercontent.com/assets/11324072/6497734/285ab498-c2be-11e4-8037-653da9421e33.png)

**Comment by abuckle** [comment]
Service works too... :)

Anthony

![screenshot from 2015-03-04 22 40 33](https://cloud.githubusercontent.com/assets/11324072/6497827/8463936c-c2bf-11e4-9133-ab1856823d4e.png)

**Comment by salfter** [comment]
Once I included those three additional files, autotools quit complaining, configure did its job, and it looks like the compile was successful.  I've submitted a pull request that adds them in.

Now I just need to incorporate the changes into the ebuild now as a workaround of sorts until they get checked in here...almost have that sorted.
