### ISSUE TITLE
move Merged Mining

### ISSUE THREAD

**Issue by Rav3nPL** [unobtanium-official/Unobtanium#14]
As there MM is NOT working and there is NO schedule to start it, MM code should be moved from master to separate branch.

**Comment by bryceweiner** [comment]
Please read the code.  Merged mining doesn't start until block 600,000, or sometime in May.  That value can be reverted to INT_MAX and put on hold indefinately should such a need arise.  It is irresponsible to not allow for at least 60 days of public testing and disucssion prior to such an integration.  Thank you for your continued support!
