### ISSUE TITLE
unobtaniumd crashes mining AuxPOW

### ISSUE THREAD

**Issue by crackfoo** [unobtanium-official/Unobtanium#15]
Can you add this fix to the repo?

https://bitcointalk.org/index.php?topic=527500.msg11342967#msg11342967

Thanks

**Comment by Infernoman** [comment]
has this ever been fixed?

**Comment by bryceweiner** [comment]
All outstanding pull requests have been merged into the repo.

**Comment by Shinoa-Fores** [comment]
Closing, necro thread. Can be reopened by affected parties if issue persists.
