### ISSUE TITLE
cant get unobtanium to start

### ISSUE THREAD

**Issue by Infernoman** [unobtanium-official/Unobtanium#19]
Error initializing wallet database environment /home/user/.unobtanium!
built with berkley db 4.8 on ubuntu 14.04 server edition.

**Comment by bryceweiner** [comment]
Remove the bang (!).

**Comment by Infernoman** [comment]
same thing when using --datadir=
i think the (!) is an addition from the script

**Comment by bryceweiner** [comment]
Simply remove it.

**Comment by Infernoman** [comment]
the (!) gets added in by the error. I am properly defining the working directory. The working directory is even being created when not specifying it with --datadir= but neither work. and the daemon will not start. I've removed the directory multiple times now to try and get it started.

**Comment by bryceweiner** [comment]
Please understand I am not trying to be rude and I appreciate your efforts,
however if you do not have the requisite skill set to resolve the error and
create the appropriate pull request I would recommend downloading a
precompiled binary.

Decentralization means that people solve problems and contribute to the
overall operation of the network.

That's ownership.

**Comment by Infernoman** [comment]
I am completely capable of compiling and running a daemon. as i've compiled every daemon on my pool. In the community I work with I do work to better the coin. And try to contribute as much as possible. You were the one that taught me this. And I've progressed a LOT from there. i am recompiling the daemon now. using the instructions from https://cryptoguild.qnetau.com/viewtopic.php?f=14&t=36 If I have any issues I'll let you know. I haven't ran into this problem with any of the other coins that i had compiled so I thought I would bring up the issue.

**Comment by bryceweiner** [comment]
I'm afraid I don't know what you're talking about.

I am uncertain as to your identity.

Please seek help from others in the community.

That's why we build them.

**Comment by Infernoman** [comment]
I understand your a busy man. and dont remember everyone you interact with. Especially on twitter. Disregard this issue. Recompiled using different libs and I'm running now

**Comment by Blaksmith** [comment]
@bryceweiner you are an ass man... I usually don't reply to comments when I'm looking up issues, but using THE LATEST uno git, I just compiled it THE SAME on 3 machines RUNNING THE SAME OS (Ubuntu 14.04) and ONE of them came up with this error... Get your head out of your ass about "remove the !" ... the ! is from the output of the error, NOT the directory... I happened to be able to copy a working version from one of my other nodes, and it works properly ... There IS something wrong SOMEWHERE... If you did not want to persue Infernoman's problem, then you should have just kept your mouth shut! 

Blaksmith!

**Comment by AndreyNag** [comment]
Hi. I want to use unobtaniumd and I recive this error too. 
Daemon was compilled --with-incompatible-dbd on 14.04 actualy updated Ubuntu.
Listen to you comment.
Thanks.

**Comment by Infernoman** [comment]
so from the looks of it it's an ubuntu 14.04 issue. and the bang (!) is actually in your code.
https://github.com/unobtanium-official/Unobtanium/blob/7ccdf8ff9d0ddda761afd9a4010f05e123dcd6e9/src/qt/bitcoinstrings.cpp#L191

**Comment by Shinoa-Fores** [comment]
@Infernoman Closing this, unless additional help is needed. In the future UNO community will try to be a bit more responsive in fixing issues, and B.W. is no longer maintaining this code.
