### ISSUE TITLE
No payments using daemon with p2pool merge mining

### ISSUE THREAD

**Issue by p3yot3** [unobtanium-official/Unobtanium#20]
When using the daemon for merge mining with p2pool I don't receive any payments - but when using the QT wallet, payments are received normally. This is using Xubuntu 14.04 64bit, I'm unaware if the issue is the same on other OS's.

**Comment by buechling** [comment]
Ubuntu 14.04 - no problem here

**Comment by p3yot3** [comment]
Sorry, this issue was fixed a while ago.

**Comment by AndreyNag** [comment]
> Sorry, this issue was fixed a while ago.
Is this time has come?
