### ISSUE TITLE
unobtaniumd crashes

### ISSUE THREAD

**Issue by flound1129** [unobtanium-official/Unobtanium#23]
Getting this error:

**\* Error in `unobtaniumd': double free or corruption (fasttop): 0x00007fc3ac0253c0 ***

**Comment by shinohai** [comment]
I haven't reproduced this but try: export MALLOC_CHECK_=0 before running unobtaniumd again.

**Comment by Shinoa-Fores** [comment]
Closing issue, non-reproducible event.
