### ISSUE TITLE
paymentrequest.pb.h: No such file or directory

### ISSUE THREAD

**Issue by buechling** [unobtanium-official/Unobtanium#24]
make fails:

  CXX      qt/test/qt_test_test_unobtanium_qt-test_main.o
In file included from qt/test/../paymentserver.h:35:0,
                 from qt/test/paymentservertests.h:8,
                 from qt/test/test_main.cpp:12:
qt/test/../paymentrequestplus.h:8:31: fatal error: paymentrequest.pb.h: No such file or directory
 #include "paymentrequest.pb.h"
                               ^
compilation terminated.

solution:
./configure --without-gui

**Comment by Shinoa-Fores** [comment]
Closing, since solution was offered but for future archaeologists this occurs when protobuf isn't detected.
