### ISSUE TITLE
missing bits in getauxblock

### ISSUE THREAD

**Issue by djayr** [unobtanium-official/Unobtanium#31]
Getauxblock output for Unobtanium is like

{
"target": "000000000000000000000000000000000000000025f517000000000000000000",
"hash": "947430409f2735a557b918f219b19567d339a4fcd4c93ef9e463b787fc52ba31",
"chainid": 117
}

Look how it's for namecoin

{
"hash": "574f20c7b2b1f810e9d7adf5b72af031112fc51bd770608b6bafd694b3efa0c7",
"chainid": 1,
"previousblockhash": "0f9188f13cb7b2c71f2a335e3a4fc328bf5beb436012afca590b1a11466e2206",
"coinbasevalue": 5000000000,
"bits": "207fffff",
"height": 1,
"_target": "0000000000000000000000000000000000000000000000000000000000ffff7f"
}

[nBits field in bitcoin block header] (https://bitcoin.org/en/developer-reference#target-nbits)

Can you please add "bits" in getauxblock output ?

**Comment by Flurbos** [comment]
Added Here.
https://github.com/Flurbos/Unobtanium/commit/a0ced420b244ecbdc50ffb3ef8809c3616e233d7

This hasn't been compiled into any release binaries yet.
But you can compile source from master branch ( on flurbos github ) and its fixed ( Gitian building also works for master on flurbos ).

**Comment by Shinoa-Fores** [comment]
Closing, fix by @Flurbos  was merged.
