### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by sslazio2009** [unobtanium-official/Unobtanium#38]
some detail info：

ecwrapper.cpp:73:31: error: invalid use of incomplete type ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
     if (!BN_mod_mul(sor, ecsig->s, rr, order, ctx)) { ret=-1; goto err; }

bignum.h:57:24: error: invalid use of incomplete type ‘BIGNUM {aka struct bignum_st}’
 class CBigNum : public BIGNUM

bignum.h:62:9: error: ‘BN_init’ was not declared in this scope
         BN_init(this);

**Comment by Shinoa-Fores** [comment]
What ssl version are you using? Likely build will work if you use the depends/ system instead of the ssl in repos.

**Comment by Shinoa-Fores** [comment]
Closing issue, as was likely due to incompatible SSL version.
