### ISSUE TITLE
deposit problem...

### ISSUE THREAD

**Issue by asmrony88** [unobtanium-official/Unobtanium#40]
i deposit my UNO coin from coinexchange.io to bleutrade about 1day 5 hours  ago.... i didn't check the announcement for delisting UNO at 15.07.19 .... i saw status active & deposit my UNO coin .....it show explorer & 400 confirmation is past but coin doesn't deposit yet....help me to deposit... Amount : 4.79367356 UNO TX id : 16c3d06d616967780006a53a2812e4776fa82fb2d4acf760557f9093040c11f6

no one from support team & telegram admin didn't reply me...please help me...

**Comment by JSKitty** [comment]
This isn't the right place to put this, write a support ticket to Bleutrade or Coinexchange. This is the coin's development repository for the desktop wallet.

**Comment by Shinoa-Fores** [comment]
Closing as unrelated.
