### ISSUE TITLE
Uno Wallet Not Connecting

### ISSUE THREAD

**Issue by magiktree** [unobtanium-official/Unobtanium#46]
My uno wallet is not connecting.

Mac OSX - firewall is off.

my unobtanium.conf file says this:

rpcuser=unobtaniumrpc
rpcpassword=pass
#regtest=1

addnode=104.238.177.115
addnode=139.180.166.203
addnode=72.89.49.243

... And i tried this on console:

<img width="707" alt="Screenshot 2021-03-02 at 10 04 19" src="https://user-images.githubusercontent.com/79907212/109632193-aae11a80-7b3e-11eb-9b1e-a81d4dc82830.png">

**Comment by Shinoa-Fores** [comment]
Cannot reproduce and have not heard back from OP. No other users have reported, so closing for now.
