### ISSUE TITLE
missing isscript in validateaddress

### ISSUE THREAD

**Issue by cipig** [unobtanium-official/Unobtanium#48]
For addresses that are not mine, neither watchonly, `validateaddress` output is missing the `isscript` field:

```
unobtanium-cli validateaddress ucoajxr5KTy3mUMd465q8ZuvqLqhSCUeYY
{
    "isvalid" : true,
    "address" : "ucoajxr5KTy3mUMd465q8ZuvqLqhSCUeYY",
    "scriptPubKey" : "76a914c3f710deb7320b0efa6edb14e3ebeeb9155fa90d88ac",
    "ismine" : false,
    "iswatchonly" : true,
    "isscript" : false,
    "account" : ""
}

unobtanium-cli validateaddress DNuWZERohfvaKMAGGvLxH3qaJgZexxY8tk
{
    "isvalid" : true,
    "address" : "DNuWZERohfvaKMAGGvLxH3qaJgZexxY8tk",
    "scriptPubKey" : "a914c2e07d2550451e9979f2a4f14d336ac2ad29b34087",
    "ismine" : false
}
```

Can this please be added? It would make it possible to add UNO to https://github.com/KomodoPlatform/atomicDEX-Desktop

**Comment by Shinoa-Fores** [comment]
Yes this is being worked on, it appears the p2sh implementation is a bit incomplete and the field was not added. Will leave this issue open until a fix is merged.

**Comment by WikiMin3R** [comment]
Greetings - Following up on the above. We are working on integrating UNO in the AtomicDEX... this is one of the prerequisites. If fix can be devised in the near future, we will be able to move forward with implementation!
