### ISSUE TITLE
NULL DATA

### ISSUE THREAD

**Issue by padenmoss** [unobtanium-official/Unobtanium#52]
Since Bitcoin 0.9.0 arbitrary data could be inserted utilizing the OP_RETURN or before by substituting the hashed public key in P2PKH.

Remove insertion on Unobtanium.

**Comment by padenmoss** [comment]
Do auxpow operators have the concensus to share a `jump` tag?

**Comment by Shinoa-Fores** [comment]
Submit a PR or clarify this issue. Closing for now, irrelevant.
